version: "3.9"
services:
  app:
    build: .
    command: yarn dev
    ports:
      - 3000:3000
    volumes:
      - .:/code
    depends_on:
      - "db"

  db:
    container_name: "market_db"
    hostname: "postgresmarket"
    image: "postgres"
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${market}
